//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> OrderdetalID { get; set; }
        public Nullable<double> starRate { get; set; }
        public string commentDescription { get; set; }
        public int UserID { get; set; }
        public Nullable<int> CommentorUserID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
