//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredPost
    {
        public int RequiredPostID { get; set; }
        public Nullable<System.DateTime> postTime { get; set; }
        public string postDescription { get; set; }
        public string postName { get; set; }
        public string postImg { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> requiredQTY { get; set; }
        public Nullable<int> estimatePrice { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<bool> isPast { get; set; }
        public string county { get; set; }
        public string district { get; set; }
        public string address { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
